ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'IDENTITY_THEFT';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'GOLF_CART';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'RENTAL_HOME';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'RENTAL_CONDO';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'MANUFACTURED_HOME';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'CONDO';